blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/jalcantarab/v0-vibecodex/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/jalcantarab/v0-vibecodex/discussions/new?category=q-a
    about: Ask the community for help
  - name: Report a Security Vulnerability
    url: https://github.com/jalcantarab/v0-vibecodex/security/policy
    about: Please report security vulnerabilities here
